openapi: 3.0.0
info:
  title: CRUD Desafio Teppa Backend
  description: CRUD simples de um sistema de biblioteca.
  version: 1.0.0

paths:
  /accounts/users:
    post:
      tags:
        - Accounts
      summary: Criação de usuários.
      description: |
        Rota para adicionar usuários ao banco de dados.

        A senha enviada deve respeitar as seguintes regras:
        * Conter no mínimo 1 letra maiúscula.
        * Conter no mínimo 1 número.
        * Conter no mínimo 1 símbolo.
        * Ter no mínimo 8 caracteres.
        * Não conter sequências (1,2,3 | abc) de 3 ou mais dígitos.

      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreationRequest"
      responses:
        201:
          description: Sucesso!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        400:
          $ref: "#/components/responses/BadRequest"
        5XX:
          $ref: "#/components/responses/Unexpected"
  /accounts/sessions:
    post:
      tags:
        - Accounts
      summary: Login de usuário.
      description: |
        Rota para autenticar usuários.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        201:
          description: Sucesso!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        400:
          $ref: "#/components/responses/BadRequest"
        404:
          $ref: "#/components/responses/NotFound"
        5XX:
          $ref: "#/components/responses/Unexpected"
  /books:
    get:
      tags:
        - Books
      summary: Listagem de livros.
      description: Rota para listagem e busca de livros.
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: |
            Palavra chave para a busca dos livros no banco de dados.
            * Pesquisa por títulos, editoras e autores.
      responses:
        200:
          description: Sucesso!
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: "#/components/schemas/BookList"
        500:
          $ref: "#/components/responses/Unexpected"
    post:
      tags:
        - Books
      summary: Criação de livros.
      description: |
        Rota para a adicionar os livros à biblioteca.
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookRequest"
      responses:
        201:
          description: Sucesso!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookResponse"
        400:
          $ref: "#/components/responses/BadRequest"
        401:
          $ref: "#/components/responses/Unauthorized"
        5XX:
          $ref: "#/components/responses/Unexpected"

  /books/{id}:
    put:
      tags:
        - Books
      summary: Atualização de livros.
      description: Atualiza todos os dados de um livro.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          description: id do livro.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookRequest"
      responses:
        200:
          description: Sucesso!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookResponse"
        400:
          $ref: "#/components/responses/BadRequest"
        401:
          $ref: "#/components/responses/Unauthorized"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/Unexpected"
    delete:
      tags:
        - Books
      summary: Exclusão de livros.
      description: Rota para deletar um livro no banco de dados.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          description: id do livro.
          required: true
          schema:
            type: string
      responses:
        204:
          description: Sucesso!
        401:
          $ref: "#/components/responses/Unauthorized"
        500:
          $ref: "#/components/responses/Unexpected"

components:
  schemas:
    BookList:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        author:
          type: string
        publisher:
          type: string
        edition:
          type: string
        synopsis:
          type: string
      example:
        id: 'lafghlhfgahflkj'
        title: 'O Senhor dos Anéis: A Sociedade do Anel'
        author: 'J.R.R. Tolkien'
        publisher: 'Harper Collins'
        edition: '2019'
        synopsis: |
          O volume inicial de O Senhor dos Anéis, lançado originalmente em julho de 1954,
          foi o primeiro grande épico de fantasia moderno, conquistando milhões de leitores
          e se tornando o padrão de referência para todas as outras obras do gênero até hoje.
          A imaginação prodigiosa de J.R.R. Tolkien e seu conhecimento profundo das antigas
          mitologias da Europa permitiram que ele criasse um universo tão complexo e convincente
          quanto o mundo real.

    BookRequest:
      type: object
      properties:
        title:
          type: string
        author:
          type: string
        publisher:
          type: string
        edition:
          type: string
        synopsis:
          type: string
      example:
        title: 'O Senhor dos Anéis: A Sociedade do Anel'
        author: 'J.R.R. Tolkien'
        publisher: 'Harper Collins'
        edition: '2019'
        synopsis: |
          O volume inicial de O Senhor dos Anéis, lançado originalmente em julho de 1954,
          foi o primeiro grande épico de fantasia moderno, conquistando milhões de leitores
          e se tornando o padrão de referência para todas as outras obras do gênero até hoje.
          A imaginação prodigiosa de J.R.R. Tolkien e seu conhecimento profundo das antigas
          mitologias da Europa permitiram que ele criasse um universo tão complexo e convincente
          quanto o mundo real.

    BookResponse:
      allOf:
        - $ref: "#/components/schemas/BookRequest"
        - type: object
          properties:
            id:
              type: string;
          example:
            id: adf8df02fgouh

    Error:
      type: object
      properties:
        message:
          type: string
        status:
          type: string
      example:
        message: Something went wrong!
        status: error

    UserCreationRequest:
      type: object
      properties:
        name:
          type: string

        lastName:
          type: string

        email:
          type: string
          format: email

        password:
          type: string
          format: secret

        passwordConfirmation:
          type: string
          format: secret

      example:
        name: 'foo'
        lastName: 'bar'
        email: foobar@example.com
        password: '*******'
        passwordConfirmation: '*******'


    UserResponse:
      type: object
      properties:
        id:
          type: string

        name:
          type: string

        lastName:
          type: string

        email:
          type: string
          format: email

      example:
        id: adf8df02fgouh
        name: 'foo'
        lastName: 'bar'
        email: foobar@example.com

    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
          fortmat: secret
      example:
        email: user@example.com
        password: "*******"

    LoginResponse:
      type: object
      properties:
        user:
          type: object
          schema:
            $ref: "#components/schemas/UserResponse"
        token:
          type: string
      example:
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

  responses:
    Unauthorized:
      description: |
        Unauthorized

        Autenticação necessária para acessar a rota.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    BadRequest:
      description: |
        Bad Request
        Existe algum problema com os dados fornecidos na requisição.

        * Os dados não respeitam as regras de negócio.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    NotFound:
      description: |
        O recurso não foi encontrado.

      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    Unexpected:
      description: |
        Internal Server Error

        Erro interno do servidor gerado por algum comportamento inesperado.

      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
